site_name: "2019 SANS HHC Write-Up"
site_author: Thomas Bouve
copyright: Thomas Bouve - <a href="https://twitter.com/crahan">@CraHan</a>
theme:
  name: mkdocs
  highlightjs: true
  #hljs_style: solarized-light
  #hljs_style: solarized-dark
  #hljs_style: tomorrow-night
  #hljs_style: tomorrow
  #hljs_style: atom-one-light
  hljs_style: gruvbox-light
  #hljs_style: hybrid
  #hljs_style: railscasts
  hljs_languages:
    - python
    - css
    - powershell
    - bash
extra_css:
  - css/extra.css
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: "#"
nav:
- Welcome: 'index.md'
- Objectives:
  - Talk to Santa & Find the Turtle Doves: 'objectives/o1.md'
  - Unredact Threatening Document: 'objectives/o2.md'
  - Evaluate Attack Outcome: 'objectives/o3.md'
  - Determine Attacker Technique: 'objectives/o4.md'
  - Determine Compromised System: 'objectives/o5.md'
  - Splunk: 'objectives/o6.md'
  - Get Access to the Steam Tunnels: 'objectives/o7.md'
  - Bypassing the Frido Sleigh CAPTEHA: 'objectives/o8.md'
  - Retrieve Scraps of Paper from Server: 'objectives/o9.md'
  - Recover Cleartext Document: 'objectives/o10.md'
  - Open the Sleigh Shop Door: 'objectives/o11.md'
  - Filter Out Poisoned Data Sources:  'objectives/o12.md'
- Terminal Hints:
  - Bushy Evergreen - Escape Ed: 'hints/h3.md'
  - SugarPlum Mary - Linux Path: 'hints/h4.md'
  - Sparkle Redberry - Xmas Cheer Laser: 'hints/h5.md'
  - Tangle Coalbox - Frosty Keypad: 'hints/h6.md'
  - Minty Candycane - Holiday Hack Trail: 'hints/h7.md'
  - Alabaster Snowball - Nyanshell:  'hints/h8.md'
  - Pepper Minstix - Graylog: 'hints/h9.md'
  - Holly Evergreen - Mongo Pilfer: 'hints/h10.md'
  - Kent Tinseltooth - Smart Braces: 'hints/h11.md'
  - Wunorse Openslae - Zeek JSON Analysis: 'hints/h12.md'
- Miscellaneous:
  - Interesting UI Elements: 'misc/interesting_ui.md'
  - Progress Tokens: 'misc/progress_tokens.md'
  - User Accounts: 'misc/user_accounts.md'
- Scripts: 'scripts.md'
