site_name: KringleCon 2019 Write-Up
site_author: Thomas Bouve
copyright: Thomas Bouve - <a href="https://twitter.com/crahan">@CraHan</a>
theme:
  name: mkdocs
  highlightjs: true
  #hljs_style: solarized-light
  #hljs_style: solarized-dark
  #hljs_style: tomorrow-night
  #hljs_style: tomorrow
  #hljs_style: atom-one-light
  hljs_style: gruvbox-light
  #hljs_style: hybrid
  #hljs_style: railscasts
  hljs_languages:
    - python
    - css
    - powershell
    - bash
extra_css:
  - css/extra.css
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: "#"
nav:
- TL;DR: 'index.md'
- Challenges:
  - Talk to Santa & Find the Turtle Doves: 'challenges/c1.md'
  - Unredact Threatening Document: 'challenges/c2.md'
  - Evaluate Attack Outcome: 'challenges/c3.md'
  - Determine Attacker Technique: 'challenges/c4.md'
  - Determine Compromised System: 'challenges/c5.md'
  - Splunk: 'challenges/c6.md'
  - Get Access to the Steam Tunnels: 'challenges/c7.md'
  - Bypassing the Frido Sleigh CAPTEHA: 'challenges/c8.md'
  - Retrieve the Scraps of Paper from Server: 'challenges/c9.md'
  - Recover Cleartext Document: 'challenges/c10.md'
  - Open the Sleigh Shop Door: 'challenges/c11.md'
  - Filter Out Poisoned Data Sources:  'challenges/c12.md'
- Hints:
  - Bushy Evergreen - "Escape Ed": 'hints/h3.md'
  - SugarPlum Mary - "Linux Path": 'hints/h4.md'
  - Sparkle Redberry - "Xmas Cheer Laser": 'hints/h5.md'
  - Tangle Coalbox - "Frosty Keypad": 'hints/h6.md'
  - Minty Candycane - "Holiday Hack Trail": 'hints/h7.md'
  - Alabaster Snowball - "Nyanshell":  'hints/h8.md'
  - Pepper Minstix - "Graylog": 'hints/h9.md'
  - Holly Evergreen - "Mongo Pilfer": 'hints/h10.md'
  - Kent Tinseltooth - "Smart Braces": 'hints/h11.md'
  - Wunorse Openslae - "Zeek JSON Analysis": 'hints/h12.md'
# - Scripts: 'scripts.md'
- Scripts:
  - find_code.py: 'scripts/find_code.py.md'
  - capteha_api.py: 'scripts/capteha_api.py.md'
  - token_proxy.py: 'scripts/token_proxy.py.md'
  - decrypt_pdf.py: 'scripts/decrypt_pdf.py.md'
  - match_user_agents.py: 'scripts/match_user_agents.py.md'
- Misc:
  - Interesting UI Elements: 'misc/interesting_ui.md'
  - Progress Tokens: 'misc/progress_tokens.md'
  - User Accounts: 'misc/user_accounts.md'
